defaults: &defaults
  docker:
    - image: circleci/node:13.8.0
version: 2.1

jobs:
  build:
    steps:
      - checkout
      - run:
          name: "Installing npm"
          command: npm i
      - run:
          name: "Linting application"
          command: npm run lint
    executor:
    <<: *defaults

  test:
    steps:
      - checkout
      - run:
          name: "Installing npm"
          command: npm i
      - run:
          name: "Linting application"
          command: npm run lint
      - run:
          name: "Running test suites"
          command: npm run test
    executor:
    <<: *defaults

  analyze:
    steps:
      - checkout
      - run:
          name: "Analaysing the application"
          command: npm audit
    executor:
    <<: *defaults

workflows:
  say-hello-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test


